name: Test Go
on: [ workflow_dispatch, push ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
    - name: Test
      uses: robherley/go-test-action@v0.1.0
      with:
        testArguments: -short ./...
        omitUntestedPackages: true
        omitPie: true
